import {Buffer} from "buffer";
window.Buffer = window.Buffer || Buffer; 
window.global = window;
import 'core-js'; 
// import * as process from 'process';
// (window as any).process = process;
// (window as any)['global'] = window;
// global.Buffer = global.Buffer || require('buffer').Buffer;
// import 'core-js/features/string/pad-start'; 
// import {Buffer} from 'buffer';
// (window).global = window;
// (window).process = {};
// (window).process = window;
// (window).process.browser = true;
// (window).process.version = '';
// (window).process.versions = { node: false };
// console.log("polyfill");
// console.log(Buffer);
// (window).global.Buffer = Buffer;
